enum MeshAssetId : s32
{
	MESH_ASSET_CHARACTER,
	MESH_ASSET_RACCOON,
	MESH_ASSET_ROBOT,
	MESH_ASSET_SKYSPHERE,
	MESH_ASSET_TOTEM,
	MESH_ASSET_SMALL_POT,
	MESH_ASSET_BIG_POT,
	MESH_ASSET_SEED,
	MESH_ASSET_WATER_DROP,
	MESH_ASSET_TRAIN,

	MESH_ASSET_MONUMENT_ARCS,
	MESH_ASSET_MONUMENT_BASE,
	MESH_ASSET_MONUMENT_TOP_1,
	MESH_ASSET_MONUMENT_TOP_2,

	MESH_ASSET_BOX,
	MESH_ASSET_BOX_COVER,	

	MESH_ASSET_COUNT
};

enum TextureAssetId : s32
{
	TEXTURE_ASSET_GROUND_ALBEDO,
	TEXTURE_ASSET_TILES_ALBEDO,
	TEXTURE_ASSET_RED_TILES_ALBEDO,
	TEXTURE_ASSET_SEED_ALBEDO,
	TEXTURE_ASSET_BARK_ALBEDO,
	TEXTURE_ASSET_RACCOON_ALBEDO,
	TEXTURE_ASSET_ROBOT_ALBEDO,

	TEXTURE_ASSET_LEAVES_MASK,

	TEXTURE_ASSET_GROUND_NORMAL,
	TEXTURE_ASSET_TILES_NORMAL,
	TEXTURE_ASSET_BARK_NORMAL,
	TEXTURE_ASSET_ROBOT_NORMAL,

	TEXTURE_ASSET_WHITE,
	TEXTURE_ASSET_BLACK,
	TEXTURE_ASSET_FLAT_NORMAL,
	TEXTURE_ASSET_WATER_BLUE,

	TEXTURE_ASSET_HEIGHTMAP,

	TEXTURE_ASSET_COUNT
};

enum MaterialAssetId : s32
{
	MATERIAL_ASSET_GROUND,
	MATERIAL_ASSET_ENVIRONMENT,
	MATERIAL_ASSET_SKY,
	MATERIAL_ASSET_CHARACTER,
	MATERIAL_ASSET_SEED,
	MATERIAL_ASSET_TREE,
	MATERIAL_ASSET_WATER,
	MATERIAL_ASSET_RACCOON,
	MATERIAL_ASSET_ROBOT,
	MATERIAL_ASSET_SEA,
	MATERIAL_ASSET_LEAVES,
	MATERIAL_ASSET_BOX,

	MATERIAL_ASSET_COUNT	
};

enum AnimationAssetId : s32
{
	AAID_RACCOON_EMPTY,

	AAID_CHARACTER_IDLE,
	AAID_CHARACTER_CROUCH,
	AAID_CHARACTER_WALK,
	AAID_CHARACTER_RUN,
	AAID_CHARACTER_JUMP,
	AAID_CHARACTER_FALL,

	AAID_COUNT
};

enum SkeletonAssetId : s32
{
	SAID_CHARACTER,
	SAID_COUNT
};